language: bash
services: docker

env:
  global:
    - secure: HH86xYMthvy99v5HycaxWIhKKeRyhN8gGdfGwyY4bq1CK31aI6pLdeElCOX05kURSzNBqnDFa9u0ttH239erDm/u49I0kQMyO8gvG8ug0mtIFIF6irxBlUSb/200nBgLHCv8/h/njIQNHxPDibM87wZPTSG9/e73EBv6azOnOF8+vNVAbbxK/JEvElGTn6sDlCVSHlF/AbkKWGGzs2vZoTV5Dzn8KKGr50cc67yPvRB11KWcDuq/BA/MncWKr6bo9u/ZlPZ/ib81I9sFEGg/GmsuwnFSZvSJTV1T3HmLNyPq2dI5ug25gbN422j2JccjKhY14d5zRaOTRPiIgsrJw2DXRRbb3v6GN/phNaqo7KNiiRxixE4ei1UyISrAGeehMyXXIv9MUQoBqThXi/DnqyLzmkjUwSSJtn6ptc6NGCHTT/YnZqHXNqNvfsOWuI/WnnTDey1vjVNYg52DWkT+HnJ9+kk2iS/adAykedwg19g6hkEue4qBKLJT3pldmzTE9sxnI3H8j9tT1j4ExhFnk05xOYkXdTrgoXlBFY9WqJ9AoPxEKgGOL9PFluSzmbZVrTxOWEshSjT7VJ86OKnZjXcGdsVCfg3chcA7ExibpQbv/T0oFLaTYHwRytsDKP7OheP9K3YSGS6d76JnXy4DwoW5MQsxw+cb9HURErE7qpg=
  matrix:
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.9
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.8
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.7
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.6
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.5
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.4
    - PHP_VERSION=7.2 LIBXML_VERSION=2.9.9
    - PHP_VERSION=7.2 LIBXML_VERSION=2.9.8
    - PHP_VERSION=7.2 LIBXML_VERSION=2.9.7
    - PHP_VERSION=7.2 LIBXML_VERSION=2.9.6
    - PHP_VERSION=7.2 LIBXML_VERSION=2.9.5
    - PHP_VERSION=7.2 LIBXML_VERSION=2.9.4
    - PHP_VERSION=7.1 LIBXML_VERSION=2.9.9
    - PHP_VERSION=7.1 LIBXML_VERSION=2.9.8
    - PHP_VERSION=7.1 LIBXML_VERSION=2.9.7
    - PHP_VERSION=7.1 LIBXML_VERSION=2.9.6
    - PHP_VERSION=7.1 LIBXML_VERSION=2.9.5
    - PHP_VERSION=7.1 LIBXML_VERSION=2.9.4
    - PHP_VERSION=7.0 LIBXML_VERSION=2.9.9
    - PHP_VERSION=7.0 LIBXML_VERSION=2.9.8
    - PHP_VERSION=7.0 LIBXML_VERSION=2.9.7
    - PHP_VERSION=7.0 LIBXML_VERSION=2.9.6
    - PHP_VERSION=7.0 LIBXML_VERSION=2.9.5
    - PHP_VERSION=7.0 LIBXML_VERSION=2.9.4

before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "andreskrey" --password-stdin
script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build --build-arg php_version=${PHP_VERSION} --build-arg libxml_version=${LIBXML_VERSION} -t "andreskrey/php-$PHP_VERSION-libxml-$LIBXML_VERSION" .
    )
after_script:
  - docker images
  - docker push andreskrey/php-${PHP_VERSION}-libxml-${LIBXML_VERSION}
